// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9fbGPohD6zFhd84P4gbn9MJfAEGB6D-U',
    appId: '1:708719999059:web:05504f7c346c64308faea6',
    messagingSenderId: '708719999059',
    projectId: 'is-recommender',
    authDomain: 'is-recommender.firebaseapp.com',
    storageBucket: 'is-recommender.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEJt-47JZG8Kq06lDbFH4D9aXJ8l57pDo',
    appId: '1:708719999059:android:ecf31ee1f633a4fe8faea6',
    messagingSenderId: '708719999059',
    projectId: 'is-recommender',
    storageBucket: 'is-recommender.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwHIm17uBpK33Hc7p6NkltmSERuSQCSoM',
    appId: '1:708719999059:ios:3239aeaeae9b82978faea6',
    messagingSenderId: '708719999059',
    projectId: 'is-recommender',
    storageBucket: 'is-recommender.appspot.com',
    iosBundleId: 'com.example.movieRecommender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwHIm17uBpK33Hc7p6NkltmSERuSQCSoM',
    appId: '1:708719999059:ios:3239aeaeae9b82978faea6',
    messagingSenderId: '708719999059',
    projectId: 'is-recommender',
    storageBucket: 'is-recommender.appspot.com',
    iosBundleId: 'com.example.movieRecommender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9fbGPohD6zFhd84P4gbn9MJfAEGB6D-U',
    appId: '1:708719999059:web:62ec300741f0efee8faea6',
    messagingSenderId: '708719999059',
    projectId: 'is-recommender',
    authDomain: 'is-recommender.firebaseapp.com',
    storageBucket: 'is-recommender.appspot.com',
  );
}
